Update cypress_tests.yml

diff --git a/.github/workflows/cypress_tests.yml b/.github/workflows/cypress_tests.yml
--- a/.github/workflows/cypress_tests.yml
+++ b/.github/workflows/cypress_tests.yml
@@ -80,8 +80,14 @@ jobs:
           npx wait-on http://localhost:4200
 
           echo "Run Cypress tests"
-          npx cypress run --browser chrome --project ./swt2-bsa-frontend/bogenliga
-                    
+          npx cypress run --browser chrome --project ./swt2-bsa-frontend/bogenliga --reporter junit --reporter-options "mochaFile=cypress-results/results.xml" || echo "Cypress tests failed, but pipeline continues"
+          
+      - name: Upload Cypress test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: cypress-results
+          path: cypress-results/results.xml
+          
       - name: Tests completed
         if: success()
         run: echo "Build and tests completed successfully!"
